### ISSUE TITLE
faile to make:  No targets specified and no makefile found

### ISSUE THREAD

**Issue by sunhoro** [WeixiaoGao/Roofline-extraction-from-orthophotos#1]
Hi, followed all the installation instructions but the last part keeps failing.

(roofline1) C:\Users\sunho\Roofline-extraction-from-orthophotos\kinetic_partition\build>mingw32-make
mingw32-make: *** No targets specified and no makefile found.  Stop.

I'm using Python 3.9.18 on Windows 11 and all other package versions are installed as stated.
See below for the full steps I used:

=========================================================================

(base) C:\Users\sunho>conda activate roofline1

(roofline1) C:\Users\sunho>cd C:\Users\sunho\Roofline-extraction-from-orthophotos\kinetic_partition

(roofline1) C:\Users\sunho\Roofline-extraction-from-orthophotos\kinetic_partition>mkdir build

(roofline1) C:\Users\sunho\Roofline-extraction-from-orthophotos\kinetic_partition>cd build

(roofline1) C:\Users\sunho\Roofline-extraction-from-orthophotos\kinetic_partition\build>cmake .. -DCMAKE_BUILD_TYPE=Release -DPYTHON_LIBRARY=$CONDAENV/lib/libpython3.10.so -DPYTHON_INCLUDE_DIR=$CONDAENV/include/python3.10 -DBOOST_INCLUDE_DIR=$CONDAENV/include -DEIGEN3_INCLUDE_DIR=$CONDAENV/include/eigen3 -DGMP_INCLUDE_DIR=$CONDAENV/include -DGMP_LIBRARY_RELEASE=$CONDAENV/lib/libgmp.so -DMPFR_INCLUDE_DIR=$CONDAENV/include -DMPFR_LIBRARIES=$CONDAENV/lib/libmpfr.so -DGMPXX_INCLUDE_DIR=$CONDAENV/include -DGMPXX_LIBRARIES=$CONDAENV/lib/libgmpxx.so -DCGAL_DIR=$CONDAENV/lib/cmake/CGAL -DOpenCV_DIR=$CONDAENV/lib/cmake/opencv4
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
-- The C compiler identification is MSVC 19.29.30148.0
-- The CXX compiler identification is MSVC 19.29.30148.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python: C:/Users/sunho/AppData/Local/Programs/Python/Python311/python.exe (found version "3.11.2") found components: Interpreter Development NumPy Development.Module Development.Embed
-- Found Boost: C:/Users/sunho/anaconda3/envs/roofline1/Library/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found suitable version "1.78.0", minimum required is "1.65.0") found components: filesystem numpy
-- Found GDAL: C:/Users/sunho/anaconda3/envs/roofline1/Library/lib/gdal.lib (found version "3.6.2")
-- Found OpenCV: C:/Users/sunho/anaconda3/envs/roofline1/Library (found version "4.6.0")
-- Visual Leak Detector (VLD) is not found.
-- Using header-only CGAL
-- Targeting Visual Studio 16 2019
-- Target build environment supports auto-linking
-- Using VC toolset 142.
-- Generator uses intermediate configuration directory: $(Configuration)
-- Found GMP: debug;C:/Users/sunho/anaconda3/envs/roofline1/Library/lib/gmp.lib;optimized;$CONDAENV/lib/libgmp.so
-- Found MPFR: $CONDAENV/lib/libmpfr.so
-- Found Boost: C:/Users/sunho/anaconda3/envs/roofline1/Library/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found suitable version "1.78.0", minimum required is "1.66")
-- Boost include dirs: C:/Users/sunho/anaconda3/envs/roofline1/Library/include
-- Boost libraries:
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Multi-configuration CMake generator: cannot display flags
-- Requested component: Core
-- Eigen3 path specified in cmake variable EIGEN3_INCLUDE_DIR is set to $CONDAENV/include/eigen3, but that path does not contains the file signature_of_eigen3_matrix_library and is considered as invalid.
-- NOTICE: This demo requires ?? and will not be compiled.
-- Configuring done (8.3s)
-- Generating done (0.0s)
CMake Warning:
  Manually-specified variables were not used by the project:

    BOOST_INCLUDE_DIR
    PYTHON_INCLUDE_DIR
    PYTHON_LIBRARY

-- Build files have been written to: C:/Users/sunho/Roofline-extraction-from-orthophotos/kinetic_partition/build

(roofline1) C:\Users\sunho\Roofline-extraction-from-orthophotos\kinetic_partition\build>make
'make' is not recognized as an internal or external command,
operable program or batch file.

(roofline1) C:\Users\sunho\Roofline-extraction-from-orthophotos\kinetic_partition\build>mingw32-make
mingw32-make: *** No targets specified and no makefile found.  Stop.

**Comment by WeixiaoGao** [comment]
Hi, firstly I've only tested on Ubuntu, not Windows. Secondly, I don't see any error when you build it, is the project not generated? Have you tried building it using Visual Studio?

**Comment by sunhoro** [comment]
Yes, I tried VS2019.

So I tried using "cmake -G "Visual Studio 16 2019" which generated “kinetic_partition.sln.” Then used VS2019 to build soultion. But in the end, similar issue.

**Comment by WeixiaoGao** [comment]
Could you please be more specific as to what errors VS2019 is getting in the build process?
